name: Scala CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install sbt
        run: |
          sudo apt-get update
          sudo apt-get install -y sbt
      - name: compile
        run: sbt compile
      - name: run tests
        run: sbt test
